### ISSUE TITLE
JSPM: not found

### ISSUE THREAD

**Issue by nicmendoza** [martingust/aurelia-repeat-strategies#1]
Found via https://github.com/aurelia/templating-resources/issues/41

Really hoping this works. I tried installing via jspm as described in the readme but I get the error "Repo jspm:martingust/aurelia-repeat-strategies not found.". I ended up installing like this instead
    jspm install github:martingust/aurelia-repeat-strategies

**Comment by martingust** [comment]
Thanks! Updated readme to include install through github.
