### ISSUE TITLE
Updating bound viewmodel property does not cause the rendered DOM fragment to be replaced, but appended to

### ISSUE THREAD

**Issue by nicmendoza** [martingust/aurelia-repeat-strategies#2]
If we take your example view/viewmodel pair, and extend it just a tiny bit to allow a contrived example where we update the bound property, as below, the issue is simple to replicate.

viewmodel

``` javascript
export class App {
  data = {
    "foo": {
      baz: true
    },
    "bar": {
      baz: false
    }
  }

  update(){
    this.data = {
      "foo": {
        baz: false
      },
      "bar": {
        baz: true
      }
    };
  }
}
```

view

``` html
<template>
  <div repeat.for="[key, value] of data | iterable">
    ${key} ${value.baz}
  </div>
  <button class="button" click.trigger="update()">update</button>
</template>
```

Here you can see a screenshot of the behavior after the button is pressed. Subsequent presses cause the same effect, with additional DOM fragments being appended, rather than replacing the original markup.

![image](https://cloud.githubusercontent.com/assets/5489626/13408393/9e800fce-defb-11e5-9919-e02af9eac2a9.png)

Similarly, setting the viewmodel property to undefined has no effect whatsoever (you would expect it to clear out the relevant section of DOM, but instead the DOM fragment remains in place).

Let me know if I can add any further information. I thought I'd start with a bug report, since I am not yet familiar with the internals of Aurelia.

**Comment by martingust** [comment]
In order to handle that scenario the `instanceChanged` method in the strategy would need to first remove all old views from the view slot before creating new once [here](https://github.com/martingust/aurelia-repeat-strategies/blob/master/src/iterable-repeat-strategy.js#L5) like [here](https://github.com/aurelia/templating-resources/blob/master/src/number-repeat-strategy.js#L19) in the repeater's number strategy.

**Comment by martingust** [comment]
Fixed in https://github.com/nicmendoza/aurelia-repeat-strategies/commit/fb2bd692e09c2c930f2685d85e167dfd50b25082
